import shopimg1 from "../../public/img1.png";
import shopimg2 from "../../public/img2.png";
import shopimg3 from "../../public/img3.png";
import shopimg4 from "../../public/img4.png";
import shopimg5 from "../../public/img5.png";
import shopimg6 from "../../public/img6.png";
export const process = [
  {
    id: "01",

    title: "Choose Your Product",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a t",
  },
  {
    id: "02",
    title: "Checkout",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a t",
  },
  {
    id: "03",
    title: "Making your own box",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a t",
  },
  {
    id: "04",
    title: "Delivering",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a t",
  },
  {
    id: "05",
    title: "Into your hands",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a t",
  },
];

export const sampleShopData = [
  {
    shop_id: "shop001",
    shop_name: "Green Valley Farms",
    owner: "John Silva",
    location: "Colombo, Sri Lanka",
    contact_number: "+94 712345678",
    email: "greenvalley@farmcart.com",
    ratings: 4.5,
    cover_img: shopimg1,
    delivery_fee: 150,
    products: [
      {
        product_id: "prod001",
        product_name: "Organic Tomatoes",
        category: "Vegetables",
        price_per_kg: 300,
        available_quantity_kg: 50,
      },
      {
        product_id: "prod002",
        product_name: "Fresh Spinach",
        category: "Vegetables",
        price_per_bunch: 50,
        available_quantity_bunch: 100,
      },
    ],
    subscription_plans: [
      {
        plan_id: "sub001",
        plan_name: "Weekly Vegetable Box",
        price: 1200,
        description:
          "A curated selection of fresh vegetables delivered weekly.",
      },
    ],
  },
  {
    shop_id: "shop002",
    shop_name: "Nature's Bounty",
    owner: "Priya Fernando",
    location: "Kandy, Sri Lanka",
    contact_number: "+94 723456789",
    email: "naturesbounty@farmcart.com",
    ratings: 4.7,
    cover_img: shopimg2,
    delivery_fee: 200,
    products: [
      {
        product_id: "prod003",
        product_name: "Mangoes",
        category: "Fruits",
        price_per_kg: 600,
        available_quantity_kg: 30,
      },
      {
        product_id: "prod004",
        product_name: "Bananas",
        category: "Fruits",
        price_per_dozen: 200,
        available_quantity_dozen: 50,
      },
    ],
    subscription_plans: [
      {
        plan_id: "sub002",
        plan_name: "Monthly Fruit Box",
        price: 2200,
        description: "A variety of fresh seasonal fruits delivered monthly.",
      },
    ],
  },
];

export const shopList = [
  {
    shop_id: "shop001",
    shop_name: "Green Valley Farms",
    owner: "John Silva",
    location: "Colombo, Sri Lanka",
    contact_number: "+94 712345678",
    email: "greenvalley@farmcart.com",
    ratings: 4.5,
    cover_img: shopimg1,
    delivery_fee: 150,
  },
  {
    shop_id: "shop002",
    shop_name: "Nature's Bounty",
    owner: "Priya Fernando",
    location: "Kandy, Sri Lanka",
    contact_number: "+94 723456789",
    email: "naturesbounty@farmcart.com",
    ratings: 4.7,
    cover_img: shopimg2,
    delivery_fee: 200,
  },
  {
    shop_id: "shop003",
    shop_name: "Sunny Meadows",
    owner: "Rajitha Perera",
    location: "Galle, Sri Lanka",
    contact_number: "+94 734567890",
    email: "sunnymeadows@farmcart.com",
    ratings: 4.2,
    cover_img: shopimg3,
    delivery_fee: 180,
  },
  {
    shop_id: "shop004",
    shop_name: "Harvest Haven",
    owner: "Nalini Kumar",
    location: "Matara, Sri Lanka",
    contact_number: "+94 756789012",
    email: "harvesthaven@farmcart.com",
    ratings: 4.6,
    cover_img: shopimg4,
    delivery_fee: 160,
  },
  {
    shop_id: "shop005",
    shop_name: "Fresh Fields",
    owner: "Dilan Jayasinghe",
    location: "Negombo, Sri Lanka",
    contact_number: "+94 765432109",
    email: "freshfields@farmcart.com",
    ratings: 4.4,
    cover_img: shopimg5,
    delivery_fee: 170,
  },
  {
    shop_id: "shop006",
    shop_name: "Orchard Grove",
    owner: "Samantha Weerasinghe",
    location: "Anuradhapura, Sri Lanka",
    contact_number: "+94 783456789",
    email: "orchardgrove@farmcart.com",
    ratings: 4.3,
    cover_img: shopimg5,
    delivery_fee: 190,
  },
  {
    shop_id: "shop007",
    shop_name: "Garden Delight",
    owner: "Sanjeewa Silva",
    location: "Jaffna, Sri Lanka",
    contact_number: "+94 792345678",
    email: "gardendelight@farmcart.com",
    ratings: 4.5,
    cover_img: shopimg6,
    delivery_fee: 210,
  },
  {
    shop_id: "shop008",
    shop_name: "Farm Fresh",
    owner: "Chamali Ranasinghe",
    location: "Batticaloa, Sri Lanka",
    contact_number: "+94 712345679",
    email: "farmfresh@farmcart.com",
    ratings: 4.1,
    cover_img: shopimg3,
    delivery_fee: 200,
  },
  {
    shop_id: "shop009",
    shop_name: "Nature's Harvest",
    owner: "Ajantha Perera",
    location: "Ratnapura, Sri Lanka",
    contact_number: "+94 723456780",
    email: "naturesharvest@farmcart.com",
    ratings: 4.8,
    cover_img: shopimg4,
    delivery_fee: 220,
  },
  {
    shop_id: "shop010",
    shop_name: "Organic Oasis",
    owner: "Nadeesha Fernando",
    location: "Kegalle, Sri Lanka",
    contact_number: "+94 734567891",
    email: "organicoasis@farmcart.com",
    ratings: 4.4,
    cover_img: shopimg5,
    delivery_fee: 190,
  },
  {
    shop_id: "shop011",
    shop_name: "Pure Produce",
    owner: "Vijay Kumar",
    location: "Puttalam, Sri Lanka",
    contact_number: "+94 745678901",
    email: "pureproduce@farmcart.com",
    ratings: 4.6,
    cover_img: shopimg6,
    delivery_fee: 210,
  },
  {
    shop_id: "shop012",
    shop_name: "Green Garden",
    owner: "Ravi Kumara",
    location: "Kalutara, Sri Lanka",
    contact_number: "+94 756789012",
    email: "greengarden@farmcart.com",
    ratings: 4.3,
    cover_img: shopimg1,
    delivery_fee: 180,
  },
  {
    shop_id: "shop013",
    shop_name: "Eco Farms",
    owner: "Kumara Alwis",
    location: "Vavuniya, Sri Lanka",
    contact_number: "+94 765432108",
    email: "ecofarms@farmcart.com",
    ratings: 4.7,
    cover_img: shopimg2,
    delivery_fee: 220,
  },
];

export const testimonials = [
  {
    id: "testimonial001",
    name: "Amelia Johnson",
    position: "CEO, Johnson's Kitchen",
    photo: "https://example.com/images/amelia-johnson.jpg",
    text: "FarmCart has completely transformed the way I shop for fresh produce. The quality and convenience are unparalleled!",
  },
  {
    id: "testimonial002",
    name: "Michael Smith",
    position: "CEO, Johnson's Kitchen",
    photo: "https://example.com/images/michael-smith.jpg",
    text: "I love the variety and freshness of the products available on FarmCart. The delivery service is prompt and reliable.",
  },
  {
    id: "testimonial003",
    name: "Sophia Lee",
    position: "CEO, Johnson's Kitchen",
    photo: "https://example.com/images/sophia-lee.jpg",
    text: "FarmCart offers an excellent selection of fruits and vegetables. The user-friendly platform and quick delivery make it a favorite in my household.",
  },
];
